# Generated by Django 4.1.1 on 2023-01-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('model', models.CharField(choices=[('LTE', 'FireTV Stick Lite'), ('REG', 'FireTV Stick'), ('F4K', 'FireTV Stick 4K'), ('MAX', 'FireTV Stick 4k Max'), ('CUB', 'FireTV Cube'), ('OMN', 'FireTV Omni Series Smart TV'), ('OTH', 'Other device')], default='REG', max_length=3)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_payment', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Account', to='clients.client')),
            ],
            options={
                'verbose_name': 'FireTV Account',
                'ordering': ('-last_payment',),
            },
        ),
    ]
