# Generated by Django 4.1.1 on 2023-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
