# Generated by Django 4.1.1 on 2023-01-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accts', '0004_alter_account_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_balance',
            new_name='balance',
        ),
    ]
