# Generated by Django 4.1.1 on 2023-01-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_account_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
