# Generated by Django 4.1.1 on 2023-01-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Account',
            new_name='account',
        ),
    ]
