# Generated by Django 4.1.1 on 2023-01-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_account_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.CharField(choices=[('CSH', 'Cash'), ('CRD', 'Credit/Debit Card'), ('PPL', 'PayPal'), ('TRN', 'Bank Transfer'), ('OTH', 'Other')], default='CSH', max_length=3),
        ),
    ]
